### ISSUE TITLE
Problems with scotty-format-0.1.0.0

### ISSUE THREAD

**Issue by hvr** [potomak/scotty-format#3]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues...

For one, the `description` ("Please see README.md") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists (and currently it doesn't exist); therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

The other thing is that the build-dependencies have inaccurate versions bounds. Specifically, I've noticed the following compile error(s)

```
Configuring component lib from scotty-format-0.1.0.0
Preprocessing library scotty-format-0.1.0.0...
[1 of 1] Compiling Web.Scotty.Format.Trans ( src/Web/Scotty/Format/Trans.hs, /tmp/matrix-worker/1480280541/dist-newstyle/build/x86_64-linux/ghc-7.8.4/scotty-format-0.1.0.0/build/Web/Scotty/Format/Trans.o )

src/Web/Scotty/Format/Trans.hs:67:10:
    Not in scope: type constructor or class ‘Applicative’

src/Web/Scotty/Format/Trans.hs:71:10:
    Not in scope: type constructor or class ‘Monoid’
    Perhaps you meant ‘Monad’ (imported from Prelude)
cabal: Failed to build scotty-format-0.1.0.0 (which is required by
exe:scotty-format-example from scotty-format-0.1.0.0).
```

or e.g.

```
Configuring component lib from scotty-format-0.1.0.0
Preprocessing library scotty-format-0.1.0.0...
[1 of 1] Compiling Web.Scotty.Format.Trans ( src/Web/Scotty/Format/Trans.hs, /tmp/scotty-format-0.1.0.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/scotty-format-0.1.0.0/build/Web/Scotty/Format/Trans.o ) [Network.HTTP.Media changed]

src/Web/Scotty/Format/Trans.hs:16:39:
    Module ‘Network.HTTP.Media’ does not export ‘mapAcceptMedia’
cabal: Failed to build scotty-format-0.1.0.0 (which is required by
exe:scotty-format-example from scotty-format-0.1.0.0).
```

If you have any questions, please let me know!

**Comment by potomak** [comment]
@hvr thanks for opening this issue.

I will update the `description`, I just left the one included by stack by default because I was lazy.

Using stack `lts-6.15`, the one listed in the `stack.yaml`, I can build the package without any error. I tried to build it with `lts-7.10` and I didn't get any error as well. I can't find the dependencies versions used by Hackage buildbot during the failed build. I can't find the failed build at https://hackage.haskell.org/package/scotty-format as well. Is there a way I can find more information on the failed build?

**Comment by hvr** [comment]
@potomak The problem is that Stackage snapshots are just a small set of isolated data-points in the huge configuration space that is accessible to the cabal solver. 

You can't find more details about the failed builds publicly yet, because they are the result of the next-gen work-in-progress version of http://matrix.hackage.haskell.org/; the first counter-example was a result of compiling with GHC 7.8.4 + base-4.7, whereas the 2nd counter-example was using some early `http-media` version (iirc version 0.1). In the future this information will be easy to access for everyone.

**Comment by potomak** [comment]
@hvr I updated both package description and dependencies versions, I uploaded the two new versions to Hackage. Now that version boundaries are stricter the build should succeed, but please tell me if it doesn't. Thanks for your feedback.

**Comment by hvr** [comment]
@potomak I'm afraid the `base >= 4.8.2 && < 4.9` constraint is a bit too tight (as it excludes GHC 8.0); you probably wanted `base >= 4.8.2 && < 4.10`.

Below is a screenshot of the current situation which may help understand the effect better;
Also note that you can edit the meta-data only without having to upload a full new release via e.g.
https://hackage.haskell.org/package/scotty-format-0.1.0.2/scotty-format.cabal/edit

![untitled](https://cloud.githubusercontent.com/assets/285533/20652738/303ce4a8-b4ff-11e6-891d-76f7ec7cba3a.png)
